export {default as member1 } from "./member1.jpeg";
export {default as member2 } from "./member2.jpeg";
export {default as member3 } from "./member3.jpeg";
export {default as member4 } from "./member4.jpg";
export {default as hero} from "./hero.jpeg";
export {default as about_image} from "./about.jpeg";
export {default as property} from "./property.png";
export {default as giz} from "./giz.jpeg";
export {default as florax} from "./florax.png";
export {default as kings} from "./kings.jpg";
export {default as blog1} from "./blog1.jpg";
export {default as blog2} from "./blog2.jpg";
export {default as blog3} from "./blog3.jpg";