export {default as member1 } from "./member1.jpeg";
export {default as member2 } from "./member2.jpeg";
export {default as member3 } from "./member3.jpeg";
export {default as member4 } from "./member4.png";
export {default as profile2} from "./profile-2.jpeg";
export {default as profile3} from "./profile-3.jpeg";
export {default as profile4} from "./profile-4.jpeg";
export {default as profile5} from "./profile-5.jpg";
export {default as profile6} from "./profile-6.png";
export {default as hero} from "./hero.jpeg";
export {default as about_image} from "./about.jpeg";
export {default as building_1} from "./building-1.jpeg";
export {default as building_2} from "./building-2.jpeg";
export {default as building_3} from "./building-3.jpeg";
export {default as building_4} from "./building-4.jpeg";
export {default as property} from "./property.png";
export {default as giz} from "./giz.jpeg";
export {default as florax} from "./florax.png";
export {default as kings} from "./kings.jpg";
export {default as building_9} from "./building-9.jpeg";
export {default as building_10} from "./building-10.jpeg";
export {default as blog1} from "./blog1.jpg";
export {default as blog2} from "./blog2.jpg";
export {default as blog3} from "./blog3.jpg";